# Generated by Django 5.1.7 on 2025-06-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBVM_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=130),
        ),
    ]
