# Generated by Django 5.1.7 on 2025-06-18 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SBVM_app', '0002_user_created_at_user_is_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Student',
        ),
    ]
