# Generated by Django 5.1.7 on 2025-06-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBVM_app', '0003_rename_user_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bottle_count',
            field=models.IntegerField(default=0),
        ),
    ]
