# Generated by Django 5.1.7 on 2025-06-19 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SBVM_app', '0003_studenttoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_active',
        ),
    ]
