# Generated by Django 5.1.7 on 2025-06-18 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SBVM_app', '0004_student_bottle_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_active',
        ),
    ]
